version: '3.8'
services:
  api-dev:
    container_name: api-dev
    build: 
      context: ./server
      dockerfile: Dockerfile.dev
    restart: unless-stopped
    ports:
      - 3001:3001
    volumes:
      - ./server/src:/app/src
    env_file:
      - ./server/.env
    depends_on:
      - mongo

  mongo:
    container_name: mongodb
    image: mongo:5.0.5
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    restart: always


volumes:
  mongodb:
